spring.application.name=produto
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb://localhost:27017/Produto
server.port = 8080
